name: my_plugin_web
description: Web implementation of the my_plugin plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

flutter:
  plugin:
    implements: my_plugin
    platforms:
      web:
        pluginClass: MyPluginWeb
        fileName: my_plugin_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  my_plugin_platform_interface:
    path: ../my_plugin_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0
