name: {{project_name.snakeCase()}}_android
description: Android implementation of the {{project_name.snakeCase()}} plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.1"

flutter:
  plugin:
    implements: {{project_name.snakeCase()}}
    platforms:
      android:
        package: {{org_name.dotCase()}}
        pluginClass: {{project_name.pascalCase()}}Plugin
        dartPluginClass: {{project_name.pascalCase()}}Android

dependencies:
  flutter:
    sdk: flutter
  {{project_name.snakeCase()}}_platform_interface:
    path: ../{{project_name.snakeCase()}}_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.2
