name: my_plugin
description: A very good Flutter federated plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: my_plugin_android
      ios:
        default_package: my_plugin_ios
      macos:
        default_package: my_plugin_macos
      linux:
        default_package: my_plugin_linux
      web:
        default_package: my_plugin_web
      windows:
        default_package: my_plugin_windows

dependencies:
  flutter:
    sdk: flutter
  my_plugin_android:
    path: ../my_plugin_android
  my_plugin_ios:
    path: ../my_plugin_ios
  my_plugin_linux:
    path: ../my_plugin_linux
  my_plugin_macos:
    path: ../my_plugin_macos
  my_plugin_platform_interface:
    path: ../my_plugin_platform_interface
  my_plugin_web:
    path: ../my_plugin_web
  my_plugin_windows:
    path: ../my_plugin_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.1.0
