name: my_plugin_windows
description: Windows implementation of the my_plugin plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.1"

flutter:
  plugin:
    implements: my_plugin
    platforms:
      windows:
        pluginClass: MyPluginWindows
        dartPluginClass: MyPluginWindows

dependencies:
  flutter:
    sdk: flutter
  my_plugin_platform_interface:
    path: ../my_plugin_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
