name: {{project_name.snakeCase()}}_platform_interface

on:
  pull_request:
    paths:
      - ".github/workflows/{{project_name.snakeCase()}}_platform_interface.yaml"
      - "src/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}_platform_interface/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/{{project_name.snakeCase()}}_platform_interface.yaml"
      - "src/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}_platform_interface/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.0.0
      working_directory: src/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}_platform_interface
