name: {{project_name.snakeCase()}}_platform_interface

on:
  pull_request:
    paths:
      - ".github/workflows/{{project_name.snakeCase()}}_platform_interface.yaml"
      - "{{project_name.snakeCase()}}_platform_interface/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/{{project_name.snakeCase()}}_platform_interface.yaml"
      - "{{project_name.snakeCase()}}_platform_interface/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.2
      working_directory: {{project_name.snakeCase()}}_platform_interface
{{#publishable}}
  pana:
    uses: VeryGoodOpenSource/very_good_workflows/brick/__brick__/{{project_name.snakeCase()}}/.github/workflows/pana.yml@v1
{{/publishable}}
