name: {{#snakeCase}}{{project_name}}{{/snakeCase}}_windows
description: Windows implementation of the {{#snakeCase}}{{project_name}}{{/snakeCase}} plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    implements: {{#snakeCase}}{{project_name}}{{/snakeCase}}
    platforms:
      windows:
        pluginClass: {{#pascalCase}}{{project_name}}{{/pascalCase}}Windows
        dartPluginClass: {{#pascalCase}}{{project_name}}{{/pascalCase}}Windows

dependencies:
  flutter:
    sdk: flutter
  {{#snakeCase}}{{project_name}}{{/snakeCase}}_platform_interface:
    path: ../{{#snakeCase}}{{project_name}}{{/snakeCase}}_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
