name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

{{> plugin_platforms.dart }}

dependencies:
  flutter:
    sdk: flutter
{{> plugin_dependencies.dart }}

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^2.4.0
