name: {{#snakeCase}}{{project_name}}{{/snakeCase}}_windows

on:
  pull_request:
    paths:
      - ".github/workflows/{{#snakeCase}}{{project_name}}{{/snakeCase}}_windows.yaml"
      - "src/{{#snakeCase}}{{project_name}}{{/snakeCase}}_windows/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/{{#snakeCase}}{{project_name}}{{/snakeCase}}_windows.yaml"
      - "src/{{#snakeCase}}{{project_name}}{{/snakeCase}}_windows/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 2.10.1
      working_directory: src/{{#snakeCase}}{{project_name}}{{/snakeCase}}_windows
