name: {{#snakeCase}}{{project_name}}{{/snakeCase}}
description: {{{description}}}
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: {{#snakeCase}}{{project_name}}{{/snakeCase}}_android
      ios:
        default_package: {{#snakeCase}}{{project_name}}{{/snakeCase}}_ios
      macos:
        default_package: {{#snakeCase}}{{project_name}}{{/snakeCase}}_macos
      linux:
        default_package: {{#snakeCase}}{{project_name}}{{/snakeCase}}_linux
      web:
        default_package: {{#snakeCase}}{{project_name}}{{/snakeCase}}_web
      windows:
        default_package: {{#snakeCase}}{{project_name}}{{/snakeCase}}_windows

dependencies:
  flutter:
    sdk: flutter
  {{#snakeCase}}{{project_name}}{{/snakeCase}}_android:
    path: ../{{#snakeCase}}{{project_name}}{{/snakeCase}}_android
  {{#snakeCase}}{{project_name}}{{/snakeCase}}_ios:
    path: ../{{#snakeCase}}{{project_name}}{{/snakeCase}}_ios
  {{#snakeCase}}{{project_name}}{{/snakeCase}}_linux:
    path: ../{{#snakeCase}}{{project_name}}{{/snakeCase}}_linux
  {{#snakeCase}}{{project_name}}{{/snakeCase}}_macos:
    path: ../{{#snakeCase}}{{project_name}}{{/snakeCase}}_macos
  {{#snakeCase}}{{project_name}}{{/snakeCase}}_platform_interface:
    path: ../{{#snakeCase}}{{project_name}}{{/snakeCase}}_platform_interface
  {{#snakeCase}}{{project_name}}{{/snakeCase}}_web:
    path: ../{{#snakeCase}}{{project_name}}{{/snakeCase}}_web
  {{#snakeCase}}{{project_name}}{{/snakeCase}}_windows:
    path: ../{{#snakeCase}}{{project_name}}{{/snakeCase}}_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^2.4.0
