name: {{project_name.snakeCase()}}_platform_interface
description: A common platform interface for the {{project_name.snakeCase()}} plugin.
version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
