name: my_plugin_macos
description: MacOS implementation of the my_plugin plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: my_plugin
    platforms:
      macos:
        pluginClass: MyPluginPlugin
        dartPluginClass: MyPluginMacOS

dependencies:
  flutter:
    sdk: flutter
  my_plugin_platform_interface:
    path: ../my_plugin_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0
