name: my_plugin_windows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/my_plugin_windows.yaml"
      - "src/my_plugin/my_plugin_windows/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/my_plugin_windows.yaml"
      - "src/my_plugin/my_plugin_windows/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.13.2
      working_directory: src/my_plugin/my_plugin_windows
