name: my_plugin_linux

on:
  pull_request:
    paths:
      - ".github/workflows/my_plugin_linux.yaml"
      - "src/my_plugin/my_plugin_linux/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/my_plugin_linux.yaml"
      - "src/my_plugin/my_plugin_linux/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.1
      working_directory: src/my_plugin/my_plugin_linux
